version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik-dynamic.yaml:/etc/traefik/traefik-dynamic.yaml:ro

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      #- "traefik.http.routers.whoami.rule=Host(`ubuntu.devxdemo.civo.com || PathPrefix(`/whoami`)"

  cerebro:
    # A container that exposes an API to show its IP address
    image: ashoka007/random-bg-color
    environment:
      - "HOSTNAME=cerebro"
    deploy:
      mode: replicated
      replicas: 2
    labels:
      - "traefik.http.routers.cerebro.rule=PathPrefix(`/cerebro`)"
      - "traefik.http.routers.cerebro.middlewares=mw-errorpages,mw-stripprefix-c"
      - "traefik.http.middlewares.mw-stripprefix-c.stripprefix.prefixes=/cerebro"
  # Error Pages Middleware
      - "traefik.http.middlewares.mw-errorpages.errors.status=400-599"
      - "traefik.http.middlewares.mw-errorpages.errors.service=error"
      - "traefik.http.middlewares.mw-errorpages.errors.query=/{status}.html"

  qualex:
    # A container that exposes an API to show its IP address
    image: ashoka007/random-bg-color
    environment:
      - "HOSTNAME=qualex"
    labels:
      - "traefik.http.routers.qualex.rule=PathPrefix(`/qualex`)"
      - "traefik.http.routers.qualex.middlewares=mw-errorpages,mw-compress,mw-ratelimit,mw-retry,mw-circuitbreaker,mw-stripprefix-q"
      - "traefik.http.middlewares.mw-stripprefix-q.stripprefix.prefixes=/qualex"
    # Error Pages Middleware
      - "traefik.http.middlewares.mw-errorpages.errors.status=400-599"
      - "traefik.http.middlewares.mw-errorpages.errors.service=error"
      - "traefik.http.middlewares.mw-errorpages.errors.query=/{status}.html"
    # Compress
      - "traefik.http.middlewares.mw-compress.compress=true"
    # Rate-limit (10 per min)
      - "traefik.http.middlewares.mw-ratelimit.ratelimit.average=10"
      - "traefik.http.middlewares.mw-ratelimit.ratelimit.period=1m"
    # Retry
      - "traefik.http.middlewares.mw-retry.retry.attempts=4"
      - "traefik.http.middlewares.mw-retry.retry.initialinterval=2s"
    # Circuit-breaker (25% of errors are 5XX or 30% network errors or average latency > 100ms)
      - "traefik.http.middlewares.mw-circuitbreaker.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100 || ResponseCodeRatio(500, 600, 0, 600) > 0.25 || NetworkErrorRatio() > 0.30"

  # Error Page service
  error:
    image: guillaumebriday/traefik-custom-error-pages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error.rule=Host(`error.ubuntu.devxdemo.civo.com`)"
      - "traefik.http.services.error.loadbalancer.server.port=80"
      - "traefik.http.routers.error.service=error"
      - "traefik.http.routers.error.entrypoints=web"

